### ISSUE TITLE
کی اماده میشه؟

### ISSUE THREAD

**Issue by ImanIranNejad** [GFW-knocker/gfw_resist_tls_proxy#1]
درود عزیز خیلی کارت درسته  من از الان هر چند ساعت رفرش میکنم ببینم به کجا رسیده و کی میتونیم استفاده کنیم از این ایده زیبات

**Comment by mehdisa99875** [comment]
سلام دمتون گرم ک تلاش می‌کنید اینترنت آزاد فراهم بشه    انشالله بسرعت  کدشو  بزنید   و هر روز پخته ترش کنید تا این gfw ب زانو دربیاد ❤️🌹

**Comment by GFW-knocker** [comment]
بزودی میاریم رو ایکس ری
خبر میدیم
مرسی
