### ISSUE TITLE
Idea: Randomizing the length of fragments

### ISSUE THREAD

**Issue by Argo160** [GFW-knocker/gfw_resist_tls_proxy#10]
First of all thanks for sharing this brilliant idea
what if everyone use the default settings and say all the fragments being 77 by length all over the net.
the firewall will recognise and drop all the packets having size of 77. isnt it?
so isnt better to make it randomized length?

**Comment by GFW-knocker** [comment]
yes of course.
we choose 77 because ASCII characters of SNI seems to be corrupted and undetectable
this script is for demonstration purpose.
soon we add all ideas of fragmenting into v2ray
with many options including your idea

**Comment by SaintShit** [comment]
I've set L_fragment = 300, just for test, to see what if I send the client hello packet completely. Although the sni characters isn't splitted in data, it's working!! I wonder why. (I'm sure that my domain is filtered BTW)

![image](https://user-images.githubusercontent.com/118110306/234267253-31ce6f1a-2aec-4786-8067-ebc4d3cab63e.png)
![image](https://user-images.githubusercontent.com/118110306/234267270-a7491f48-01c4-49bb-8c66-fab12eb04e77.png)
![image](https://user-images.githubusercontent.com/118110306/234267413-b6a517d4-b03f-43a3-bf6e-fead2a5f256d.png)
