### ISSUE TITLE
به روز نبودن ویدئوها

### ISSUE THREAD

**Issue by Alinuxir** [GFW-knocker/gfw_resist_tls_proxy#107]
درود

بنده به یک اشکال خیلی بزرگ برخوردم و اینکه یوتیوب که باز میشه
و مراجعه میکنم به مثلا یک کانال که دنبال میکنم آخرین ویدئویی که
میبینم ارسال شده مربوط به ۹ ماه پیش بوده !!! درصورتیکه آخرین ارسالی
اون کانال با وی پی ان مربوط به ۳ روز پیش بوده !!!
و برای اکثر کانالها همین اتفاق میافته که ویدئوهای جدید نشون داده نمیشه
و تاریخ ارسالها برمیگرده به ماهها قبل 
 بروزر را در مود اینکوگنیتو هم همیشه باز میکنم

**Comment by GFW-knocker** [comment]
سلام.
لینک کانالی که این مشکل رو داره بذارید بررسی تا بررسی بشه.
و این issue مربوط به اون یکی پروژه اس . چرا اینجا issue زدید؟

**Comment by GFW-knocker** [comment]
@Alinuxir 

سلام.
لینک کانالی که این مشکل رو داره بذارید بررسی تا بررسی بشه.
و این issue مربوط به اون یکی پروژه اس . چرا اینجا issue زدید؟

**Comment by Alinuxir** [comment]
درود بله متاسفانه اشتباه شد ولی متاسفانه امکان حذف پست رو ندارم

امکانش هست منتقل بفرمایید به اون پروژه یا حذف بفرمایید تا دراون
پروژه ایجاد کنم ... شرمنده

مثلا لینک کانال جادی عزیز ... پادکست آخرش با این برنامه شما که 
زحمت کشدید لود نمیشه و نشون داده نمیشه با سرور خودم که متصل بشم
پادکست آخری میاد مجدد بعد از رفرش صفحه
https://www.youtube.com/@JadiMirmirani/videos

**Comment by GFW-knocker** [comment]
@Alinuxir 

بله تست کردم همینطوره 
خیلی عجیبه که سرورهای گوگل sync نیستن با هم
لطفا رو اون پروژه هم issue بدید
