### ISSUE TITLE
اینترنت آزاد 

### ISSUE THREAD

**Issue by mehdisa99875** [GFW-knocker/gfw_resist_tls_proxy#2]
سلام دمتون گرم ک تلاش میکنید برای اینترنت ازاد ❤️ انشالله هرچی زودتر کدش زده بشه و هر روز پخته ترش کنید🌹

**Comment by poriyakhoshhemmat** [comment]
اقا ی مشتی زدین تو دهنشون که برن سال دیگه برگردن
خیلی عشقین
خیلی دمتون گرمه
گل کاشتین
