### ISSUE TITLE
سلام وقت بخیر دوست عزیز به نظر میرسه داده هایی که تبادل میشه بین کاربر و سرور رمزنگاری نمیشه و شخص ثالث می‌تونه راحت بخونه این داده هارو 

### ISSUE THREAD

**Issue by Szxcc** [GFW-knocker/gfw_resist_tls_proxy#25]

**Comment by GFW-knocker** [comment]
بیخیال 
ما فقط از این ور میگیریم اونور رایت میکنیم
کانفیگ تون چک کنید tls داشته باشه

**Comment by Szxcc** [comment]
داداش میتونی تغیراتی در کد اعمال کنی که این داده های رد و بدل شده بین سرور و کاربر رو رمزنگاری کنه

**Comment by Szxcc** [comment]
اوکیه داش من تغییرات تو کد اعمال کردم همون برا خودم استفاده میکنم .. راستی خسته نباشی و دستت درد کنه
