### ISSUE TITLE
تانل زدن

### ISSUE THREAD

**Issue by alijoon3376** [GFW-knocker/gfw_resist_tls_proxy#4]
سلام توسعه دهنده عزیز 
ایا امکانش هست با این روش روی سرور ایرانمون این تاخیرو ایجاد کنیم که بتونیم ترافیکو به ایپی های کلودفلر بفرستیم ؟

**Comment by hangman1998** [comment]
اره دیگه میتونین تو سرور ایران این اسکریپت رو اجرا کنین
