### ISSUE TITLE
Not working on Mobinnet

### ISSUE THREAD

**Issue by Mehdiv97** [GFW-knocker/gfw_resist_tls_proxy#51]
سلام داداش با تست های که روی مبین نت انجام دادم فقط sent انجام میشه و هیچ داده ایی نمیشه دریافت کرد و کار نمیکنه روی گوشی

**Comment by GFW-knocker** [comment]
رو گوشی فعلا سخته setup کردنش
شایدم مبین نت مثل ایرانسله
