### ISSUE TITLE
Not Working?!

### ISSUE THREAD

**Issue by thecyanide** [GFW-knocker/gfw_resist_tls_proxy#56]
the script works and sends data with the default cloudflare ip provided in the code (162.159.135.42)
but when i replace it with a dirty ip like "172.67.193.36", it does not send at all. tested on mci and asiatech and both have the same result.

**Comment by GFW-knocker** [comment]
thats cloudflare issue
not all port available on all ip
and some ip work allocated for some country

**Comment by thecyanide** [comment]
oh yeah my bad sorry i just checked and the ip i was testing with didnt have port 2053 open. tested with a different ip and now it actually tries to send.
while i understand that this is in super early stages, adding logs for these kind of stuff would make this project a bit more polished and noob friendly.
thank you for this project and your effort <3
