### ISSUE TITLE
grps too slow

### ISSUE THREAD

**Issue by yunesxinus** [GFW-knocker/gfw_resist_tls_proxy#62]
سلام ممنون از زحماتتون
من روی کانفیگ grpc 
خیلی کند وصل میشه و هر ده ثانیه یکبار قطع میشه و دوباره وصل میشه اتصال پایدار نیست ولی ایپی سالم میزارم داخل کد بجای ایپی دیفالت شما سرعت خیلی خوب میشه

**Comment by GFW-knocker** [comment]
این برا کانفیگ وب سوکت هست و دورزدن ایپی کثیف کلودفلر و دامنه فیلتر شده
شما وقتی ایپی تمیز داری دیگه نیازی به ما نداری
با ایپی تمیز وصل هستی دیگه

**Comment by yunesxinus** [comment]
من وب سوکت میزنم روی هیچ پورتی وصل نمیشه برای همین از grpc استفاده میکنم
