### ISSUE TITLE
VPN Mode or Tun

### ISSUE THREAD

**Issue by bahrammm1995** [GFW-knocker/gfw_resist_tls_proxy#63]
تو برنامه های nekoray رو حالت vpn mode یا v2rayNG حالت Tun، کار نمیکنه؟

**Comment by none57** [comment]
با دسترسی ادمین اینو بزن

**Comment by none57** [comment]
با دسترسی ادمین اینو بزن تو cmd قبل از اجرا بزن حتما ایپی رو هم میتونی عوض کنی و ایپی گتوی اینترنت خودت با ایپی کلود فلر خودت عوض کنی

route add 162.159.135.42/32 192.168.1.1 metric 1

**Comment by bahrammm1995** [comment]
ممنون درست شد
