### ISSUE TITLE
رفع مشکل vpn mode

### ISSUE THREAD

**Issue by megapiz** [GFW-knocker/gfw_resist_tls_proxy#70]
سلام خداقوت دمتون گرم 
میشه لطفا کد رو بگونه تفییر بدید که هم از tcp و udp بشه استفاده کرد چون این کد فعلا فقط رو حالت system proxy روی nekoray کار میکنه، من به حالت vpn mode تو برنامه نیاز دارم تا بتونم از بعضی نرم افزار ها و سایت ها که به اتصال udp نیازه استفاده کنم.

**Comment by GFW-knocker** [comment]
برا حالت vpn mode باید برنامه پایتون رو استثنا کنید
یعنی ترافیک پایتون دوباره برنگرده تو nekoray
بتونه مستقیم بره

**Comment by megapiz** [comment]
لطفا راهنمایی کنید چطور اینکار رو انجام بدم!
