### ISSUE TITLE
vpn mode

### ISSUE THREAD

**Issue by mohammad6006** [GFW-knocker/gfw_resist_tls_proxy#8]
سلام تو حالت عادی خوب کار میکنه ولی وقتی مثلا روی nekoray میزارم به حالت vpn mode کار نمیکنه 
احتمالا باید پراسسی رو توی تنظیمات وی پی ان بایپس کنم

**Comment by GFW-knocker** [comment]
بله روی مد وی پی ان ترافیک خود پایتون میاد دوباره توی  نکوری

**Comment by EbrahimTahernejad** [comment]
you can bypass python.exe, python3.exe in your tunnel settings for now

**Comment by VahidAssar** [comment]
I am using nekoray on macos and really do not know how to bypass python.exe and python3.exe in this case. Would you please eliminate how to make correct configuration on macos?

**Comment by mohammad6006** [comment]
> I am using nekoray on macos and really do not know how to bypass python.exe and python3.exe in this case. Would you please eliminate how to make correct configuration on macos?

VPN setting -> Bypass Process Name:
```
pythonw.exe
py.exe
python3.exe
python.exe
```

![image](https://user-images.githubusercontent.com/553379/234555079-b9f58b77-95c6-40c2-934a-eabf2986aea0.png)
