### ISSUE TITLE
Import custom config in nekoray ?

### ISSUE THREAD

**Issue by fromseer** [GFW-knocker/gfw_resist_tls_proxy#85]
سلام دوستان، لطفا میشه یکی بگه چطوری میتونم کانفیگ یوتیوب رو به برنامه nekoray در ویندوز ایمپورت کنم؟

منظورم این کانفیگ هست https://github.com/GFW-knocker/gfw_resist_tls_proxy/blob/main/youtube/youtube_config.json

**Comment by GFW-knocker** [comment]
> سلام دوستان، لطفا میشه یکی بگه چطوری میتونم کانفیگ یوتیوب رو به برنامه nekoray در ویندوز ایمپورت کنم؟

منم گشتم نداشت انگار.
از v2rayN استفاده کنید.

**Comment by TKZ2009** [comment]
> سلام دوستان، لطفا میشه یکی بگه چطوری میتونم کانفیگ یوتیوب رو به برنامه nekoray در ویندوز ایمپورت کنم؟
> 
> منظورم این کانفیگ هست https://github.com/GFW-knocker/gfw_resist_tls_proxy/blob/main/youtube/youtube_config.json

باید بزنی اد سرور
بعد بزاری رو کاستوم بعد بزاری json بعد کد رو پیست کنی و وصل شی

**Comment by TKZ2009** [comment]
> > سلام دوستان، لطفا میشه یکی بگه چطوری میتونم کانفیگ یوتیوب رو به برنامه nekoray در ویندوز ایمپورت کنم؟
> 
> منم گشتم نداشت انگار.
> از v2rayN استفاده کنید.

nekoray میدونم حداقل تو چند اپدیت اخریش کاستوم کانفیگ داره که هم میشه کد sing box باشه هم میشه کانفیگ json باشه

**Comment by alisamadi60** [comment]
یه قدم دیگه بعد کپی پیست مونده و اینکه برای نکوری باید پورت ها رو عوض کنی. وقتی فایل رو باز کردی پورت ساکس رو به 2080 و پورت اچ تی تی پی رو به 2081 باید تغییر بدی.
